name: opticks
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pint
  - strictyaml
  - numpy
  - scipy >=1.13.0
  - python=3.12
  # packages needed for testing and automation
  - pytest
  - pytest-xdist
  - coverage
  # packages needed for document generation
  - matplotlib
  - sphinx
  - ipykernel
  - nbsphinx
  - sphinx-notfound-page
  - sphinx-hoverxref
  - sphinx_rtd_theme
  - pip
  - pip:
      - prysm
        # packages needed for document generation
      - myst_parser
      - sphinx_autodoc_typehints
      - sphinx_copybutton
      # packages needed for testing and automation
      - tox
      - tox-conda