name: opticks
channels:
  - conda-forge
  - nodefaults
dependencies:
  - astropy
  - portion
  - strictyaml
  - numpy
  - scipy >=1.13.0
  - python >=3.11
  # packages needed for testing and automation
  - pytest
  - pytest-xdist
  - coverage
  # packages needed for document generation
  - matplotlib
  - sphinx
  - ipykernel
  - sphinx-notfound-page
  - sphinx-hoverxref
  - sphinx_rtd_theme
  - pip
  - pip:
      # Use the latest development version of prysm
      # - prysm
      - git+https://github.com/brandondube/prysm.git
        # packages needed for document generation
      - myst_parser
      - sphinx_autodoc_typehints
      - sphinx_copybutton
      - nbsphinx
      # packages needed for testing and automation
      - tox
      - tox-conda
      - black[jupyter]