# This is the setup file for the tox tool
[tox]
description = tox environments list
envlist =
    py311
    py312
    py313
    py314
    quicktest
    clean_coverage
    coverage
    build_docs
    linkcheck
    reformat
    codestyle


# skips packaging
skipsdist = True

# Switch to conda based (rather than pip based) environment
requires = tox-conda

[testenv]
description = run tests

allowlist_externals=
    /bin/bash
    /usr/bin/bash
    sphinx-build

deps =
    pytest
    pytest-xdist
;    -rrequirements.txt

conda_env = environment.yml
conda_install_args=
    --override-channels

commands =
    pytest {posargs:-vv --durations=0 --junitxml=test-results/test_output.xml}

[testenv:quicktest]
description = quick testing
deps =
    pytest
    pytest-xdist
commands =
    pytest {posargs:-v -n=auto}

[testenv:coverage]
description = checks coverage
deps =
    pytest
    coverage
skip_install = true
commands =
    coverage run --source opticks -m pytest
    coverage xml
    coverage report -m

[testenv:clean_coverage]
deps = coverage
skip_install = true
commands = coverage erase


[testenv:reformat]
description = reformats the code using ruff
deps =
    ruff
skip_install = true
commands =
    ruff check --fix opticks tests docs
    ruff format opticks tests docs

[testenv:codestyle]
description = checks code style using ruff and pyright
deps =
    ruff
    pyright
skip_install = true
commands =
    ruff check opticks tests docs
    ruff format --check opticks tests docs
    pyright opticks tests docs


[testenv:build_docs]
changedir = docs
description = invoke sphinx-build to build the HTML docs
setenv =
  READTHEDOCS_PROJECT = opticks
  READTHEDOCS_VERSION = latest
extras = docs
commands =
    pip freeze
    sphinx-build -W --color -b html . _build/html


[testenv:linkcheck]
changedir = docs
description = check the links in the HTML docs
extras = docs
commands =
    pip freeze
    sphinx-build -W -b linkcheck . _build/html
