# Python CircleCI 2.1 configuration file
version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@14.0.2

jobs:

  codacy-coverage-report:

    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox tox-conda
      - run:
         name: install dependencies
         command: conda env create -f environment.yml
      - run:
         name: Generate coverage data
         command: tox -e coverage      
      - run:
         name: Prepare upload
         command: conda install -y curl
      - run:
          name: Upload coverage data
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
      - coverage-reporter/send_report:
          coverage-reports: coverage.xml
          project-token: $CODACY_PROJECT_TOKEN

  
  tests:

    docker:
      - image: continuumio/miniconda3

    parallelism: 2

    steps:
      # Get repo from GitHub
      - checkout
      - run:
          name: Install tox
          command: pip install tox
     # Create venv and install dependencies - not needed as the docker image is miniconda
      - run:
         name: install dependencies
         command: conda env create -f environment.yml
      - run:
          name: Run tests
          command: | 
            set -e
            TEST_FILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
            tox -e py311 -- $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results


  codestyle:

    docker:
      - image: continuumio/miniconda3

    steps:
      # Get repo from GitHub
      - checkout
      # Create venv and install dependencies
      - run:
          name: Install Python dependencies
          command: pip install tox
      - run:
          name: Make sure style checks pass
          command: tox -e codestyle


workflows:
  tests_and_codestyle:
    jobs:
      - codacy-coverage-report
      - codestyle
      - tests