name: Codestyle Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  codestyle:
    name: Run Codestyle Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: 'latest'
        channels: conda-forge
        mamba-version: "*"
        channel-priority: true
        auto-update-conda: false
        auto-activate-base: false
        environment-file: environment.yml
        activate-environment: opticks


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tests
      run: tox
